CREATE TABLE "users_series" (
"user_id" SERIAL PRIMARY KEY,
"user_name" VARCHAR,
"username" VARCHAR
);

CREATE TABLE "users_series2" (
"user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"user_name" VARCHAR,
"username" VARCHAR
);


CREATE TABLE "users_series3" (
"user_id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"user_name" VARCHAR,
"username" VARCHAR
);

-- PRIMARY KEY COMPOSITE KEY
CREATE TABLE "users_series4" (
"user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
"user_name" VARCHAR,
"username" VARCHAR,
PRIMARY KEY ("user_id", "username")
);

-- UUID
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE "users_uuid" (
    "user_id" UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    "user_name" VARCHAR
);

-- UUID v4
CREATE TABLE "users_uuid_v4" (
    "user_id" UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    "user_name" VARCHAR
);
